### ISSUE TITLE
Update GPULayers vars

### ISSUE THREAD

**Issue by Vamoss** [amandaghassaei/gpu-io#3]
Hi Amanda,

I am trying to update the array of colors attached to the `GPULayer` after initialization.

I am referring to your example available here:
https://openprocessing.org/sketch/1760726

I already tried to invoke other methods like:
`particlesColor.setFromArray(colors);`

But the values are not updated.

I also tried different combinations of invoking `step` method by the program.

Cheers,
Carlos

**Comment by Vamoss** [comment]
I've found the solution by calling the resize method. It updated the internal array:
`particlesColor.resize(numParticles, colors);`

Cheers,
Carlos

**Comment by amandaghassaei** [comment]
both will work. I just added the following lines to the open processing demo and it worked:

```js
window.addEventListener('keydown', (e) => {
	if (e.key === 'c') {
		for (let i = 0; i < this.numParticles; i++) {
			// Set to yellow.
			this.colors[3 * i] = 1;
			this.colors[3 * i + 1] = 1;
			this.colors[3 * i + 2] = 0;
		}
		this.particlesColor.setFromArray(this.colors);
	}
});
```

You can also init a new Float32Array and pass that in:
```js
window.addEventListener('keydown', (e) => {
	if (e.key === 'c') {
		const colors = new Float32Array(this.numParticles * 3);
		for (let i = 0; i < this.numParticles; i++) {
			// Set to yellow.
			colors[3 * i] = 1;
			colors[3 * i + 1] = 1;
			colors[3 * i + 2] = 0;
		}
		this.particlesColor.setFromArray(colors);
	}
});
```

Note that for this sketch, you'll see the color slowly fade into the new color, because the particles starting adding in the new color on top of the old one, and the old colors eventually decay away.

Hope that helps!
